#+TITLE: Costco
#+FILETAGS:

* Projects
** Cranberry Cream Cheese
*** [2017-05-25 Thu 10:41]
 - Looking to get 90 days shelf life to gaurantee 60 days for Costco.
** Chicken Salad Dressing
*** [2017-07-10 Mon 10:59]
Eggless salad dressing base
 - Vendors
   - Ventura foods
   - Southern Classic
**** DONE [#A] Receive eggless salad dressing bases from Ventura Foods
     CLOSED: [2017-07-11 Tue 09:35] DEADLINE: <2017-07-11 Tue>
     - CLOSING NOTE [2017-07-11 Tue 09:35] \\
       4/1 gallon containers received on 7/11 @9:00. 2/1 gallon containers of control and 2/1 gallons containers of eggless.
**** DONE Ship Chicken, onions and celery to Southern Classic
     CLOSED: [2017-07-10 Mon 16:02] DEADLINE: <2017-07-10 Mon>
     - State "DONE"       from "SHIP"       [2017-07-10 Mon 16:02]
       //NOTE [2017-07-10 Mon 16:03]
       Shipped on 7/10. Tracking # 779593323047
**** DONE [#A] Process Ventura foods salad dressing bases with veggies
     CLOSED: [2017-07-11 Tue 11:36]
     - CLOSING NOTE [2017-07-11 Tue 11:36] \\
       4 bags of each variable were produced
 - Salad Dressing base with onions and celery only.
 - No chicken added
**** DONE [#A] Ship Ventura Foods salad dressing base out for HPP processing [2/2]:SHIP:
     CLOSED: [2017-07-11 Tue 15:18] DEADLINE: <2017-07-11 Tue>
     - State "DONE"       from "SHIP"       [2017-07-11 Tue 15:18]
 - [X] Chicken Salad Dressing with onions and celery
 - [X] Eggless Chicken Salad Dressing with onions and celery
**** SHIP [#A] Have samples sent from HPP site to Nic Lyons and Karen (R&D) [0/2]
     DEADLINE: <2017-07-13 Thu>
 - [ ] Chicken Salad Dressing [0/2]
   - [ ] Two CSD for Nic
   - [ ] One CSD for Karan
 - [ ] Eggless Chickne Salad Dressing [0/2]
   - [ ] Two eggless for Nic
   - [ ] One eggless for Karen
*** [2017-05-25 Thu 10:41]
 - Looking to get 90 days shelf life to gaurantee 60 days for Costco.
*** [2017-05-19 Fri 10:21]
 - Sensory tasting on day 60 product on 5/18.
   - Product tasted ok. Chicken had a shredded appearance. Not sure if it was just that container, or is it caused by handling during the HPP process, or is it th HPP process itself.
** Veggie Salad Dressing
*** [2017-06-05 Mon 15:25]
**** DONE [#A] Look for 2 gallon sample of eggless dressing from Sourthern Classic
     CLOSED: [2017-06-07 Wed 16:05] DEADLINE: <2017-06-06 Tue>
     - CLOSING NOTE [2017-06-07 Wed 16:05] \\
       Sample located.
*** [2017-05-25 Thu 10:56]
 - Need to taste the following items
**** CANCELLED Taste current Ventura Dressing (w/egg)             :CANCELLED:
     CLOSED: [2017-06-09 Fri 08:38] DEADLINE: <2017-05-25 Thu>
     - State "CANCELLED"  from "TODO"       [2017-06-09 Fri 08:38] \\
       I missed the tasting.
**** CANCELLED Taste Opened container of Ventura Dressing (no egg) :CANCELLED:
     CLOSED: [2017-06-09 Fri 08:39] DEADLINE: <2017-05-25 Thu>
     - State "CANCELLED"  from "TODO"       [2017-06-09 Fri 08:39] \\
       I missed the tasting.
**** CANCELLED Taste earlier version of dressing from Sheldon (no egg) :CANCELLED:
     CLOSED: [2017-06-09 Fri 08:39] DEADLINE: <2017-05-25 Thu>
     - State "CANCELLED"  from "TODO"       [2017-06-09 Fri 08:39] \\
       I missed the tasting.
*** [2017-05-25 Thu 10:41]
 - Looking to get 90 days shelf life to gaurantee 60 days for Costco.
*** [2017-05-18 Thu 10:33] 
   - Looking to increase the current shelf life of the veggie and dressing blend to 53 days various reasons such as, production scheduling, logistics, RM ordering and usage, etc.
   - Before we approach Costco for approval we need very detailed results of both organoleptic and micro data.

** Shelf Life Validation Plan
*** [2017-05-25 Thu 10:32]
 - Need to look into validating our shelf life protocol.
   - Is Chairmans buttoned up on our end?
   - What is the handling procedures at the HPP facility?
   - What is the handling procedures/testing procedures for Microlab.
     - Is it acceptable?
**** IN-PROGRESS Look into the shelf life protocol.
     DEADLINE: <r2017-06-23 Fri>

     - State "IN-PROGRESS" from "WAITING"    [2017-06-20 Tue 16:16]
     - State "WAITING"    from "IN-PROGRESS" [2017-06-19 Mon 10:23] \\
       Sent a followup note to Morgan on 6/19
** Turkey Dressing
*** [2017-06-16 Fri 13:49]
**** IN-PROGRESS [#B] Perform Freeze/thaw testing on Costco stuffing
     SCHEDULED: <2017-07-11 Tue>
 - Need to freeze costo turkey and stuffing and then stick in the fridge for 20 days to see what happens.
**** DONE Make beef queso samples                         :Benchwork:Samples:
     CLOSED: [2017-06-27 Tue 12:46] SCHEDULED: <2017-06-21 Wed>

     - CLOSING NOTE [2017-06-27 Tue 12:46] \\
       Samples sent by Aubrey on 6/26.
* Tasks

** TODO Need to perform micro testing on the Veggie and Dressing blend on day 53

** TODO Need to perform sensory analysis of veggie and dressing blend for day 53.

** DONE Ship 2 32oz Queso Mama samples to Costco                       :Ship:
   CLOSED: [2017-05-24 Wed 16:12] DEADLINE: <2017-05-22 Mon>
   - State "DONE"       from "CANCELLED"  [2017-05-24 Wed 16:13]
   - State "CANCELLED"  from "TODO"       [2017-05-24 Wed 16:12] \\
     Samples shipped on Monday 5/22 by Jen.
 - Ship Address
 - 3980 Ventura Drive
 - Suite W-100
 - Duluth GA 30096
