#+TITLE: Costco
#+FILETAGS:

* Projects
** Cranberry Cream Cheese
*** [2017-05-25 Thu 10:41]
 - Looking to get 90 days shelf life to gaurantee 60 days for Costco.
** Chicken Salad Dressing
*** [2017-05-25 Thu 10:41]
 - Looking to get 90 days shelf life to gaurantee 60 days for Costco.
*** [2017-05-19 Fri 10:21]
 - Sensory tasting on day 60 product on 5/18.
   - Product tasted ok. Chicken had a shredded appearance. Not sure if it was just that container, or is it caused by handling during the HPP process, or is it th HPP process itself.
** Veggie Salad Dressing
*** [2017-06-05 Mon 15:25]
**** DONE [#A] Look for 2 gallon sample of eggless dressing from Sourthern Classic
     CLOSED: [2017-06-07 Wed 16:05] DEADLINE: <2017-06-06 Tue>
     - CLOSING NOTE [2017-06-07 Wed 16:05] \\
       Sample located.
*** [2017-05-25 Thu 10:56]
 - Need to taste the following items
**** TODO Taste current Ventura Dressing (w/egg)
     DEADLINE: <2017-05-25 Thu>
**** TODO Taste Opened container of Ventura Dressing (no egg)
     DEADLINE: <2017-05-25 Thu>
**** TODO Taste earlier version of dressing from Sheldon (no egg)
     DEADLINE: <2017-05-25 Thu>
*** [2017-05-25 Thu 10:41]
 - Looking to get 90 days shelf life to gaurantee 60 days for Costco.
*** [2017-05-18 Thu 10:33] 
   - Looking to increase the current shelf life of the veggie and dressing blend to 53 days various reasons such as, production scheduling, logistics, RM ordering and usage, etc.
   - Before we approach Costco for approval we need very detailed results of both organoleptic and micro data.

** Shelf Life Validation Plan
*** [2017-05-25 Thu 10:32]
 - Need to look into validating our shelf life protocol.
   - Is Chairmans buttoned up on our end?
   - What is the handling procedures at the HPP facility?
   - What is the handling procedures/testing procedures for Microlab.
     - Is it acceptable?
**** TODO Look into the shelf life protocol.
     DEADLINE: <2017-06-09 Fri>


* Tasks

** TODO Need to perform micro testing on the Veggie and Dressing blend on day 53

** TODO Need to perform sensory analysis of veggie and dressing blend for day 53.

** DONE Ship 2 32oz Queso Mama samples to Costco                       :Ship:
   CLOSED: [2017-05-24 Wed 16:12] DEADLINE: <2017-05-22 Mon>
   - State "DONE"       from "CANCELLED"  [2017-05-24 Wed 16:13]
   - State "CANCELLED"  from "TODO"       [2017-05-24 Wed 16:12] \\
     Samples shipped on Monday 5/22 by Jen.
 - Ship Address
 - 3980 Ventura Drive
 - Suite W-100
 - Duluth GA 30096
