#+TITLE: Denny's

* Projects
  
** Meatloaf
*** [2017-07-18 Tue 14:17]
**** DONE Need to decide what physical measurements Cf wants to perform on Denny's Meatloaf
     CLOSED: [2017-07-19 Wed 12:19] DEADLINE: <2017-07-24 Mon>
     - CLOSING NOTE [2017-07-19 Wed 12:19] \\
       Jen set out protocal on 7/18. We are proposing pH, Fat, Moisture, and salt. These would be perfomred 2x/year.
- what do we want to measure
- How do we measure it
- What do we need to purchase to measure it
***** DONE Provide list of testing requirements for Denny's meatloaf testing
      CLOSED: [2017-07-20 Thu 09:52] DEADLINE: <2017-07-24 Mon>
      - CLOSING NOTE [2017-07-20 Thu 09:52] \\
	Sent earlier in the week to Chris.
*** [2017-06-30 Fri 15:41]
**** DONE Process 110 lbs of Denny's Meatloaf
     CLOSED: [2017-07-18 Tue 14:22]
     - State "DONE"  from "TODO"       [2017-07-18 Tue 14:22] \\
       Compled week of 7/10. Samples were sent to customer.
 - 25 loaves Cooked
   - // NOTE [2017-07-11 Tue 15:03] 24 loaves are being cooked on 7/11
 - 25 loaves Raw (No cooking). Otherwise, processed the same as cooked product. Customer will cook at store.
**** DONE [#A] Ship meatloaf samples to Denny's
     CLOSED: [2017-07-13 Thu 15:47] SCHEDULED: <2017-07-13 Thu>
     - CLOSING NOTE [2017-07-13 Thu 15:47] \\
       Shipped on 7/13 to deliver on 7/14. Fedex Tracking # is: 779626253899
       4 cases total - 2 cooked and 2 uncooked (no kitchen bouquet added)
*** [2017-06-01 Thu 11:31]
*** 
**** DONE Update Denny's Meatloaf formula
     CLOSED: [2017-06-30 Fri 15:40] DEADLINE: <2017-06-30 Fri>
     - CLOSING NOTE [2017-06-30 Fri 15:40]
update cooking temp and wip formula
*** [2017-05-26 Fri 10:57]
 - Meatloaf sous vide cooked for 65 minutes.
   - Internal temps of 3 separate loaves were 167°
 - Transferred to the sous vide chill tank.
   - Chill tank temp was 38°
   - 10:55 - Initial temp: 160°
   - 11:15 - Product temp: 85°
   - 11:30 - Product temp: 65°
   - 12:00 - Product temp: 48°
   - 12:20 - Product temp: 44°
   - 13:55 - Product temp: 36.6°a
*** [2017-05-25 Thu 14:24]
  - First meatloaf production. No major issues mixing.
  - Arlo would like to have a premixing step for step #3
**** DONE Grab 2 loaves of meat loaf and freeze them. Cook them the next day for comparisons.
     CLOSED: [2017-05-26 Fri 11:08] DEADLINE: <2017-05-26 Fri>
     - CLOSING NOTE [2017-05-26 Fri 11:08] \\
       Loaves processed on 5/26.
*** [2017-05-24 Wed 15:07]
  - First production will be on Thursday 5/25/2017.
  - Processing sheets are set at 1,000 lbs.
