#+TITLE: Leigh Oliver

* Projects
** Queso Mama Reformulation
*** [2017-07-18 Tue 12:01] Queso Mama Retail Match
- Queso Mama is rebranding it's line to expand market area.
- Mild formula 32oz.
- Need to maximize cost savings, but match Leigh Oliver glass jar product as closely as possible.
- Cannot use current formula.
**** CANCELLED Make Queso Mama (Mild) to match glass jar retail pack :CANCELLED:
     CLOSED: [2017-07-27 Thu 11:16] SCHEDULED: <2017-07-28 Fri>
     - State "CANCELLED"  from "TODO"       [2017-07-27 Thu 11:16] \\
       No longer involved with this
- New formula to match the Leigh Oliver glass retail as closely as possible.
- Product should be on the thinner side of the spec.
*** [2017-05-25 Thu 12:35]
 - Feedback from Costco buyers is product was too salty
 - Product should run on the thin side of the spec.

**** DONE Make Queso Mama Mild Queso samples with no added salt
     CLOSED: [2017-05-31 Wed 08:00] DEADLINE: <2017-05-30 Tue>

     - CLOSING NOTE [2017-05-31 Wed 08:00] \\
       Benchwork completed on 5/30.
**** DONE [#B] Make Queso Mama Mild Queso samples using Bongard cheese :Benchwork:Samples:
     CLOSED: [2017-06-27 Tue 12:31] SCHEDULED: <2017-06-20 Tue>
     - CLOSING NOTE [2017-06-27 Tue 12:31] \\
       Benchwork complete. Will ship product on Thursday 6/29
[2017-06-19 Mon 09:44] Cheese is on site.

[2017-06-05 Mon 14:35] Bongard Cheese update
Cheese should arrive this week for benchwork.

**** DONE Ship Leigh Oliver queso samples Using Bongard Cheese
     CLOSED: [2017-07-19 Wed 12:19] DEADLINE: <2017-06-23 Fri>
     - State "DONE"       from "SHIP"       [2017-07-19 Wed 12:19]
- Sample using the bongard cheese
**** DONE [#A] Update Queso Mama Mild Queso to reflect salt removal
     CLOSED: [2017-06-05 Mon 16:34] DEADLINE: <2017-06-05 Mon>
     - CLOSING NOTE [2017-06-05 Mon 16:34] \\
       Completed processing sheets.
** Queso Mama Shelf Life Study
** Beef Queso
*** [2017-06-19 Mon 10:04]
**** DONE [#B] Make sample of Beef Queso for Costco Queso Mama group
     CLOSED: [2017-06-27 Tue 12:45] SCHEDULED: <2017-06-23 Fri>
     - CLOSING NOTE [2017-06-27 Tue 12:45] \\
       Samples sent to customer by Aubrey on 6/26.
 - Queso Mama group at Costco is looking for a queso with beef.
   - NOTE [2017-06-22 Thu 13:49]
     - Had to remake product. Should have used yellow bongard, but instead used uncolored.

