#+TITLE: Life Church
* Prior Expereince
Formally trained in Jazz and Rock drumming
Play to a click track, sequenced loops, sequenced video
Studio drumming experience
Piano lessons. Can read music and drum tabs.
Various cover bands and original bands

* Prior Experience Worship Team
Drummer at Connect Christian Church (Cincinnati, Ohio) for the last 10 years.
Co-Worship Director while at connect. Involved with mentoring young musicians, coordinating auditions and providing feedback and development path.
Drummer for Artmstrong Chapel (Indian Hill, Ohio)

* Motivation for auditioning
I love being a servant for my church. I'm a musician so the most natural way for me to serve is by playing.
I love drumming in particular. I get excited about working with great teams of people and musicians.
Life is tough for a lot of people, so being part of a team that can lift people up and just worship without thinking about anything other than God is an amzaing thing to be a part of.

* My faith
I was dating a girl while I was in high school who was part of the Fellowship of Christian Athletes. She asked me to come to a meeting. Over the course of those meetings, I learned more about God. The more I learned the more I was intrigued by Him. Eventually I was saved at one of those meetings.
After going away to college I regressed away from God until I met my wife. She brought me back. I was baptized in October of 2007.
Since then I do my best for God. He's always provided for my family and for me. I've met some amazing people because of my relationship with God.

* Anything else
I'm dependable, hard working, on time.
I come prepared.
